FROM alpine:latest  as builder 
RUN apk update && apk add --no-cache bash ca-certificates

RUN wget -O wikindx.tar.bz2 https://master.dl.sourceforge.net/project/wikindx/6.11.0/wikindx_6.11.0.tar.bz2
RUN mkdir wikindx; tar jxf wikindx.tar.bz2 -C wikindx  --strip-components 1

FROM alpine:latest

RUN apk update && apk add --no-cache bash ca-certificates tini nginx

COPY --from=builder /wikindx /var/www/html/
RUN chown -R nginx /var/www/html/
RUN chgrp -R nginx /var/www/html/
ADD files/entryPoint.sh /entryPoint.sh
RUN chmod a+x /entryPoint.sh

ADD files/default.conf /etc/nginx/http.d/
RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf
RUN chown -R nginx /etc/nginx 
RUN chgrp -R nginx /etc/nginx

USER nginx


ENTRYPOINT ["/sbin/tini", "--", "/entryPoint.sh"]